### PR TITLE
When strings are frozen, we can't modify FrozenError message

### LINKED ISSUE #203: When strings are frozen, we can't modify FrozenError
### Tell us about your environment

**Ruby Version:**
2.7.1

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** 
Rails 6.1.1
Rspec 3.10.0
FactoryBot 6.1.0

**TestProf Version:**
1.0.0

### What did you do?
```ruby
# frozen_string_literal: true

require 'rails_helper'

describe 'wrong exception' do
  let_it_be(:user, freeze: true) { create(:user, email: 'quentin@example.com') }

  it 'fails spec' do
    user.email = 'francois@example.com' 
  end
end
```

### What did you expect to happen?
```
wrong exception
  fails spec (FAILED - 1)

Failures:

  1) wrong exception fails spec
     Failure/Error: user.email = 'francois@example.com'
     
     FrozenError:
       can't modify frozen attributes
     # ./spec/models/zde.rb:9:in `block (2 levels) in <top (required)>'
     # /home/quentin/.rvm/gems/ruby-2.7.1@jeancaisse/gems/webmock-3.11.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

```

### What actually happened?
```
wrong exception
  fails spec (FAILED - 1)

Failures:

  1) wrong exception fails spec
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: user.email = 'francois@example.com'
          
          FrozenError:
            can't modify frozen attributes
          # ./spec/models/zde.rb:9:in `block (2 levels) in <top (required)>'
          # /home/quentin/.rvm/gems/ruby-2.7.1@jeancaisse/gems/webmock-3.11.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: example.exception.message << TestProf::LetItBe::FROZEN_ERROR_HINT
          
          FrozenError:
            can't modify frozen String: "can't modify frozen attributes"
          # /home/quentin/.rvm/gems/ruby-2.7.1@jeancaisse/gems/test-prof-1.0.0/lib/test_prof/recipes/rspec/let_it_be.rb:246:in `block (2 levels) in <main>'
          # /home/quentin/.rvm/gems/ruby-2.7.1@jeancaisse/gems/webmock-
```

### PR DESCRIPTION
**Pull request by quentindemetz**
Fixes #203 

### Is there anything you'd like reviewers to focus on?
Is there a better strategy you'd like me to implement ? How should we get the FROZEN_ERROR_HINT to users when strings are frozen ?

### Checklist

- [ ] I've added tests for this change
- [ ] I've added a Changelog entry
- [ ] I've updated a documentation

### CODE REVIEW

**Comment by palkan** [comment]
Thanks for catching this!

> How should we get the FROZEN_ERROR_HINT to users when strings are frozen ?

Maybe, we can duplicate an error and raise a clone instead? (so, replace `raise` with `raise err_dup`)
Could you try this?

**Comment by quentindemetz** [comment]
> Maybe, we can duplicate an error and raise a clone instead? (so, replace raise with raise err_dup)
> Could you try this?

That works line 94.
However line 246 doesn't re-raise, and `example` doesn't have a `exception=` method which means I can't change the exception object there (unless you think it's a good idea to peek at the object's internals)

File: lib/test_prof/recipes/rspec/let_it_be.rb [hunk 1]
```diff
@@ -91,7 +91,7 @@ def let_it_be(identifier, **options, &block)
       initializer = proc do
         instance_variable_set(:"#{TestProf::LetItBe::PREFIX}#{identifier}", instance_exec(&block))
       rescue FrozenError => e
-        e.message << TestProf::LetItBe::FROZEN_ERROR_HINT
+        e.message << TestProf::LetItBe::FROZEN_ERROR_HINT unless e.message.frozen?
         raise
```
Comment (quentindemetz) [inline lib/test_prof/recipes/rspec/let_it_be.rb:95]:
```suggestion
        raise e.exception("#{e.message}#{TestProf::LetItBe::FROZEN_ERROR_HINT}")
```

File: lib/test_prof/recipes/rspec/let_it_be.rb [hunk 2]
```diff
@@ -243,7 +242,7 @@ def deep_freeze(record)
 RSpec.configure do |config|
   config.after(:example) do |example|
     if example.exception&.is_a?(FrozenError)
-      example.exception.message << TestProf::LetItBe::FROZEN_ERROR_HINT
+      example.exception.message << TestProf::LetItBe::FROZEN_ERROR_HINT unless example.exception.message.frozen?
```
Comment (palkan) [inline lib/test_prof/recipes/rspec/let_it_be.rb:245]: > unless you think it's a good idea to peek at the object's internals

Yeah, I think it's fine to patch something related to exceptions (because it shouldn't affect the happy path 🙂)
